// Definition below omits a couple of interesting parts like external seat

const dirs = [
  //Command
 "Squad/Parts/Command/advancedSasModuleLarge",
 "Squad/Parts/Command/avionicsNoseCone",
 "Squad/Parts/Command/cupola",
 "Squad/Parts/Command/hitchhikerStorageContainer",
 "Squad/Parts/Command/inlineAdvancedStabilizer",
 "Squad/Parts/Command/Mk1-3Pod",
 "Squad/Parts/Command/mk1Cockpits",
 "Squad/Parts/Command/mk1LanderCan",
 "Squad/Parts/Command/mk1pod",
 "Squad/Parts/Command/mk1pod_v2",
 "Squad/Parts/Command/mk2CockpitInline",
 "Squad/Parts/Command/mk2CockpitStandard",
 "Squad/Parts/Command/mk2DroneCore",
 "Squad/Parts/Command/mk2LanderCan",
 "Squad/Parts/Command/mk2LanderCan_v2",
 "Squad/Parts/Command/mk3CockpitShuttle",
 "Squad/Parts/Command/MpoProbe",
 "Squad/Parts/Command/MtmStage",
 "Squad/Parts/Command/probeCoreCube",
 "Squad/Parts/Command/probeCoreHex",
 "Squad/Parts/Command/probeCoreHex_v2",
 "Squad/Parts/Command/probeCoreOcto",
 "Squad/Parts/Command/probeCoreOcto_v2",
 "Squad/Parts/Command/probeCoreOcto2",
 "Squad/Parts/Command/probeCoreOcto2_v2",
 "Squad/Parts/Command/probeRoverBody",
 "Squad/Parts/Command/probeRoverBody_v2",
 "Squad/Parts/Command/probeStackLarge",
 "Squad/Parts/Command/probeStackSmall",
 "Squad/Parts/Command/probeStackSphere",
 "Squad/Parts/Command/probeStackSphere_v2",

 //Coupling
 "Squad/Parts/Coupling",

 //Electrical
  "Squad/Parts/Electrical/1x6ShroudSolarPanels",
 "Squad/Parts/Electrical/1x6SolarPanels",
 "Squad/Parts/Electrical/3x2ShroudSolarPanels",
 "Squad/Parts/Electrical/3x2SolarPanels",
 "Squad/Parts/Electrical/gigantorXlSolarArray",
 "Squad/Parts/Electrical/radialFlatSolarPanel",
 "Squad/Parts/Electrical/z-100Battery",
 "Squad/Parts/Electrical/z-1kBattery",
 "Squad/Parts/Electrical/z-200Battery",
 "Squad/Parts/Electrical/z-400Battery",
 "Squad/Parts/Electrical/z-4kBattery",

 //Engine
 "Squad/Parts/Engine/liquidEngine24-77",
"Squad/Parts/Engine/liquidEngine24-77_v2",
"Squad/Parts/Engine/liquidEngine48-7S",
"Squad/Parts/Engine/liquidEngine48-7S_v2",
"Squad/Parts/Engine/liquidEngineAerospike",
"Squad/Parts/Engine/liquidEngineLV-1",
"Squad/Parts/Engine/liquidEngineLV-1_v2",
"Squad/Parts/Engine/liquidEngineLV-1R",
"Squad/Parts/Engine/liquidEngineLV-909",
"Squad/Parts/Engine/liquidEngineLV-909_v2",
"Squad/Parts/Engine/liquidEngineLV-N",
"Squad/Parts/Engine/liquidEngineLV-T30",
"Squad/Parts/Engine/liquidEngineLV-T45",
"Squad/Parts/Engine/liquidEngineMainsail",
"Squad/Parts/Engine/liquidEngineMainsail_v2",
"Squad/Parts/Engine/liquidEngineMk55",
"Squad/Parts/Engine/liquidEnginePoodle",
"Squad/Parts/Engine/liquidEnginePoodle_v2",
"Squad/Parts/Engine/liquidEngineSkipper",
"Squad/Parts/Engine/liquidEngineSkipper_v2",
"Squad/Parts/Engine/liquidEngineSSME",
"Squad/Parts/Engine/MassiveSRB",
"Squad/Parts/Engine/miniJet",
"Squad/Parts/Engine/OMSEngine",
"Squad/Parts/Engine/rapierEngine",
"Squad/Parts/Engine/Size1_SRBs",
"Squad/Parts/Engine/Size2LFB",
"Squad/Parts/Engine/Size3AdvancedEngine",
"Squad/Parts/Engine/Size3EngineCluster",
"Squad/Parts/Engine/solidBoosterBACC",
"Squad/Parts/Engine/solidBoosterRT-10",
"Squad/Parts/Engine/solidBoosterRT-5",
"Squad/Parts/Engine/solidBoosterS2-17",
"Squad/Parts/Engine/solidBoosterS2-33",
"Squad/Parts/Engine/solidBoosterSep",
"Squad/Parts/Engine/SolidBoostersF",

// FuelTanks
"Squad/Parts/FuelTank/adapterTanks",
"Squad/Parts/FuelTank/drainTankFTE-1",
"Squad/Parts/FuelTank/FoilTanks",
"Squad/Parts/FuelTank/fuelTankOscarB",
"Squad/Parts/FuelTank/RCSFuelTankR1",
"Squad/Parts/FuelTank/RCSFuelTankR10",
"Squad/Parts/FuelTank/RCSFuelTankR25",
"Squad/Parts/FuelTank/RCSTankRadial",
"Squad/Parts/FuelTank/RCStankRadialLong",
"Squad/Parts/FuelTank/RockomaxTanks",
"Squad/Parts/FuelTank/Size1_Tanks",
"Squad/Parts/FuelTank/Size3Tanks",
"Squad/Parts/FuelTank/xenonTank",
"Squad/Parts/FuelTank/xenonTankLarge",
"Squad/Parts/FuelTank/xenonTankRadial",

"SquadExpansion/Serenity/Parts",
"SquadExpansion/MakingHistory/Parts"


];